# Generated by Django 3.2 on 2024-08-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria Funcional',
                'verbose_name_plural': 'Categorias Funcionais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_admissao_atual', models.DateField(verbose_name='Data de Admissão Atual')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cargo_atual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_como_atual', to='main.cargo')),
                ('cargo_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_como_inicio', to='main.cargo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoriafuncional')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['pessoa__nome'],
            },
        ),
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Divisão',
                'verbose_name_plural': 'Divisões',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Folha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ordenacao', models.IntegerField(verbose_name='Formato Ordenado')),
            ],
            options={
                'verbose_name': 'Folha',
                'verbose_name_plural': 'Folhas',
                'ordering': ['ordenacao'],
            },
        ),
        migrations.CreateModel(
            name='LocalTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Local de Trabalho',
                'verbose_name_plural': 'Locais de Trabalho',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prefeitura', models.IntegerField(unique=True, verbose_name='ID Prefeitura')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf_formatado', models.CharField(max_length=15, verbose_name='CPF Formatado')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Subdivisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Subdivisão',
                'verbose_name_plural': 'Subdivisões',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Vínculo',
                'verbose_name_plural': 'Tipos de Vínculo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.SmallIntegerField(blank=True, null=True, verbose_name='Carga Horária')),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Remuneração')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cargo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoriafuncional')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contrato')),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.divisao')),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.folha')),
                ('local_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.localtrabalho')),
                ('subdivisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subdivisao')),
                ('tipo_vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipovinculo')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['contrato__pessoa__nome', '-folha__ordenacao'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='divisao_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.divisao'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='folha_mais_recente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.folha'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='local_trabalho_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.localtrabalho'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pessoa'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='subdivisao_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subdivisao'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_vinculo_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipovinculo'),
        ),
    ]
