# Generated by Django 3.2 on 2024-08-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240828_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='id_prefeitura',
        ),
        migrations.AddField(
            model_name='contrato',
            name='id_prefeitura',
            field=models.IntegerField(default=1, unique=True, verbose_name='ID Prefeitura'),
            preserve_default=False,
        ),
    ]
